name:  Whatsapp/SMS Notify
on:
  issue_comment:
    types: created
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  page_build:
  watch:
    types: [started]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sending WhatsApp Notifcation
        uses: mdb571/wa-action@master
        with:
          from: ${{ secrets.FROM }}
          to: ${{secrets.TO }}
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH }}
      - name: Sending SMS Notification
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+1(234)5678901'
          toPhoneNumber: '+6597801671'
          message: 'Hello from Twilio'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
