name:  SMS Notify
on:
  issue_comment:
    types: created
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  page_build:
  watch:
    types: [started]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sending SMS Notification
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+1(201)9052180'
          toPhoneNumber: '+6597801671'
          message: 'Hello you have a new PUSH to github/HelloWorld'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
